### PR TITLE
Update index

### PR DESCRIPTION
**Pull request by jaydipoo7**
Please accept my pull request

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
@jaydipoo7 haven't you read the repo name or readme section. It's Naruto repo not titan repo

**Comment by jaydipoo7** [comment]
Why you marked spam !!!!! You can simply say this is not valid

**Comment by jaydipoo7** [comment]
Remove the invalid simbol it will affect my participation in hactoberfest

**Comment by jaydipoo7** [comment]
I will report you not from one but from many account see now

**Comment by vikhyatsingh123** [comment]
@jaydipoo7 which tag should I put for your pr

**Comment by jaydipoo7** [comment]
Not need of any tag thanks for removing i already made 4 PRs so no need. It is just displayed as spam in hactoberfest dashboard that's why i told you to remove nothing else :)

**Pull request closed without merging**
