### PR TITLE
Added Itachi Uchiha Image

### PR DESCRIPTION
**Pull request by ahmadncheema**

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
if you have added that, then where did you use that image

**Comment by ahmadncheema** [comment]
I committed the image to make sure git was working. I have to code setup
locally. I'll commit and push the code as soon as its completed.

**Comment by vikhyatsingh123** [comment]
ok

**Comment by ahmadncheema** [comment]
Hi There, I saw that Itachi was already present in the flip cards. I
couldn't locate "Mirai Sarutobi". So I added her flip card. I didn't add my
image to the contributors list as I thought I should ask for your
permission first.

**Comment by vikhyatsingh123** [comment]
yeah, you can add. Also delete your uploaded itachi image

**Pull request merged**
