### PR TITLE
Gamabunta Card is added

### PR DESCRIPTION
**Pull request by HarshitShukla01**
I added the card of Gamabunta.

### CODE REVIEW

**Comment by HarshitShukla01** [comment]
Can u please change label from hactoberfest to hacktoberfest.
please because it is not counting

**Comment by vikhyatsingh123** [comment]
@HarshitShukla01 resolve conflicts first. Maybe you can first fetch upstream and then create pull request

**Comment by HarshitShukla01** [comment]
Now, it's perfect

**Comment by HarshitShukla01** [comment]
I resolved the issue but you commited someone else pull request before me that is why it again start showing conflict .What can I do now

**Pull request closed without merging**
