### PR TITLE
Added Anko Mitarashi character

### PR DESCRIPTION
**Pull request by hanshulll**

### CODE REVIEW

**Comment by hanshulll** [comment]
@vikhyatsingh123 
**It will be very helpful. If your start merging the PR's🙏🏻**

**Comment by hanshulll** [comment]
@vikhyatsingh123 
**ok sure, and thank you so much and can you also please label this PR "hacktoberfest-accepted" !!**

**Comment by hanshulll** [comment]
@vikhyatsingh123 
**Thank you very much !! I am grateful to you, can you please label this PR with Hacktoberfest-accepted !! Please...**

Screenshot 2021-10-02 at 9 25 32 AM

**Comment by vikhyatsingh123** [comment]
@hanshulll I have added in the repo. So, it will count in hacktoberfest

**Comment by hanshulll** [comment]
@vikhyatsingh123 
**Thank you so much for the info🙂**

**Pull request merged**
