### PR TITLE
Update README hacktoberfest year to 2021

### PR DESCRIPTION
**Pull request by Tamir198**
I have noticed that in your readme you had this line "To contribute in Hactoberfest 2020..", its 2021 so I fixed it.

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
@Tamir198 Thanks for doing that but it will not count in hacktoberfest.

**Comment by Tamir198** [comment]
@vikhyatsingh123   _...will not count in hacktoberfest._  I actually came here just to fix the year I the readme, any reason not to accept my pr?

**Comment by vikhyatsingh123** [comment]
You can read rules of hacktoberfest for successful pr

**Comment by Tamir198** [comment]
Sure...
But thats not what i was saying 

I wanted to say that this pr is to help, not becauae of hacktoberfest

**Pull request closed without merging**
