### PR TITLE
fixed the search_button position

### PR DESCRIPTION
**Pull request by lokesh932338**
previously the search_button was appearing on the NARUTO word, and now it is fixed

### CODE REVIEW

**Comment by lokesh932338** [comment]
bro... please add the hecktoberfest-accepted label to the PR

**Comment by vikhyatsingh123** [comment]
it will be accepted

**Comment by lokesh932338** [comment]
it is not accepted....
Screenshot 2023-10-18 122126

**Comment by vikhyatsingh123** [comment]
it's accepting. I have verified it too

**Comment by lokesh932338** [comment]
does that mean it will be automatically accepted in future??, or there is some other issue?

**Comment by lokesh932338** [comment]
oh! that was some other repo, not yours... sorry for bothering...

**Pull request merged**
