### PR TITLE
fix: Social Media Handles link update along with footer credit cursor…

### PR DESCRIPTION
**Pull request by surajsingh542**
@vikhyatsingh123 Please review and merge this pr with the label of hacktoberfest-accepted.
Social Media Handles link update along with footer credit cursor ui change from arrow to pointer. Also Anko and Hamura Image Fixes. All social media handles were taken from your profile only.

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
no need of label. it will be accepted in hacktober

**Comment by surajsingh542** [comment]
> no need of label. it will be accepted in hacktober

@vikhyatsingh123 please add the label of hacktoberfest-accepted as these pr are showing as not-accepted in hacktoberfest due to not assigning the label or review done by maintainer.

**Comment by vikhyatsingh123** [comment]
wait for an hour, it will be accepted. More than 500 prs are accepted

**Comment by surajsingh542** [comment]
Ok Now it started showing a timer of 7 days for review.

Thanks for the information.

**Pull request merged**
