### PR TITLE
#2 Enhanced About Page interface and added animations to website

### PR DESCRIPTION
**Pull request by Harsh2504**
**Merge this PR after PR no. #1199** 

All **Enhancements** mentioned related **about page** in the issue were made:  Issue no. [#1168 ]
**About Page:**
1. can fix **layout & styling**
2. Fix the navbar properly by adding all tabs .

**Additional changes:**
1. Made **dark mode work properly** and **themed about page accordingly**
2. **Added animations** to _home_ and _about page_ 
3. **Added naruto sasuke fighting animation on about page**

I hope these changes will be considered for some **Good points.** I will be happy if you do so **i loved contributing to your project .**
Also consider issue raising points.

Going to shortly Create PR for Contact page too. Issue no. [https://github.com/vikhyatsingh123/Naruto-Shippuden/issues/1168 ]
**Thank You!!!**
image
image

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
Can you resolve conflicts?

**Comment by Harsh2504** [comment]
> Can you resolve conflicts?

Sorry bro I am out of town 2 days i don’t think I can make it in codepeak now 

but later I will surely resolve conflicts and create PR for you 🙌❤️ even I will try and complete your slugterra project

**Comment by vikhyatsingh123** [comment]
I have given points for these opened prs too. Whenever you will get time, try to resolve conflicts and get it merged

**Comment by Harsh2504** [comment]
> I have given points for these opened prs too. Whenever you will get time, try to resolve conflicts and get it merged

Thank you so much 🥹 you gave me unexpected surprise ‼️ i will surely complete all your PR’s . 
it means a lot 🫂

**Pull request merged**
