### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by WajihaFatim**

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
Add proper image link

**Comment by WajihaFatim** [comment]
> Add proper image link

okayy

**Comment by vikhyatsingh123** [comment]
Link is not opening. Either upload in image folder and put link of it or add another image link

**Comment by WajihaFatim** [comment]
> Link is not opening. Either upload in image folder and put link of it or add another image link

Okay

**Comment by WajihaFatim** [comment]
@vikhyatsingh123  please check if it is working now

**Pull request merged**
