### PR TITLE
Added Hagoromo

### PR DESCRIPTION
**Pull request by Indrahas**
Added Hagoromo Otsutsuki character to the index.html

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
@Indrahas resolve conflicts first. May be it can resolve by fetching upstream then doing pr

**Comment by Indrahas** [comment]
Resolved conflicts, now can you review my PR

**Comment by vikhyatsingh123** [comment]
@Indrahas not yet

**Comment by Indrahas** [comment]
can you check now?

**Pull request merged**
