### PR TITLE
Shisui Uchiha added

### PR DESCRIPTION
**Pull request by mandiraghosh783**
Hello @vikhyatsingh123 
I have added Shisui Uchiha card following the README.md file code. Kindly check and merge the PR
Here is the screenshot:
image

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
The code's template is changed now. You should follow that.

**Comment by mandiraghosh783** [comment]
Hi @vikhyatsingh123 , kindly guide me through the code as i just modified the code in README.md

**Comment by mandiraghosh783** [comment]
Kindly share the code that you want to add details of the character in. as README.md has the same code as I have written

**Comment by vikhyatsingh123** [comment]
Just look into readme section. I think you are seeing in your forked pr.

**Comment by vikhyatsingh123** [comment]
First fetch your forked repo. Then see the updated code template

**Comment by mandiraghosh783** [comment]
OK.

**Pull request closed without merging**
