### PR TITLE
Added card for character chiyo.

### PR DESCRIPTION
**Pull request by shivam222**
Added card for chiyo along with description.

### CODE REVIEW

**Comment by shivam222** [comment]
Made sure that its unique.
Also I feel we should update the description of repo from favourite character to new character.

**Comment by Unknown1243-sudo** [comment]
card changes

**Comment by Unknown1243-sudo** [comment]
`<div class="card mb-3 card-bg my-4" style="max-width: 100%;">
        <div class="row no-gutters">
            <div class="col-md-4">
                Sai
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h2 class="card-title">Sasuke Uchiha</h2>
                    <p class="card-text">Sasuke Uchiha (うちはサスケ, Uchiha Sasuke) is one of the last surviving members of Konohagakure's Uchiha clan. After his older brother, Itachi, slaughtered their clan, Sasuke made it his mission in life to avenge them by killing Itachi.
                    </p>

                </div>
            </div>
        </div>
    </div>`

**Comment by shivam222** [comment]
@Unknown1243-sudo ??

**Pull request closed without merging**
