### PR TITLE
Revert "Not found images fixed, Alignment problem fixed, problematic div(s) removed"

### PR DESCRIPTION
**Pull request by vikhyatsingh123**
Reverts vikhyatsingh123/Naruto-Shippuden#777

### CODE REVIEW

**Comment by 035pratheeksha** [comment]
Heyy!! If you dont mind can i ask you a question?

**Comment by 035pratheeksha** [comment]
@vikhyatsingh123 ?

**Comment by vikhyatsingh123** [comment]
Yes

**Comment by 035pratheeksha** [comment]
Can you please tell me in your own words how to pull/merge for hacktoberfest?

**Comment by paradoxmr24** [comment]
In your repository that you want to merge should have hacktoberfest topic added, doing this will make your repository eligible for hactoberfest, (mentioned in hactoberfest contributors guide),
then, Whenever someone make a push request on you repo you have to open the push request and click on the merge button. 
(that's it).

**Pull request merged**
